- luci-app-openclash/Makefile
Ref: project-openwrt/openwrt@c6609cf
> Avoid git pollution

- luci-app-openclash/files/usr/lib/lua/luci/controller/openclash.lua
To get current lan ip address when interface is in dhcp mode.
> To get current lan ip address

- luci-app-openclash/files/usr/share/openclash/openclash_rule.sh
> lhie1更新路径修改

- luci-app-openclash/files/etc/openclash/custom/openclash_custom_rules_2.list
- luci-app-openclash/files/usr/lib/lua/luci/model/cbi/openclash/settings.lua
- luci-app-openclash/files/usr/share/openclash/yml_rules_change.sh
- luci-app-openclash/i18n/zh-cn/openclash.zh-cn.po
增加在 Match 前添加自定义规则的选项，For Issue #172
> Add an option to allow inserting custom rules after 3rd-party rules

- luci-app-openclash/files/etc/config/openclash
- luci-app-openclash/files/etc/init.d/openclash
> remove rixcloud DoH

- luci-app-openclash/root/etc/init.d/openclash
> Fix DNS-hijacking related firewall rules

- luci-app-openclash/Makefile
- luci-app-openclash/root/etc/init.d/openclash
- luci-app-openclash/root/etc/uci-defaults/luci-openclash
**DO NOT USE SQUASH MERGE**
- feat: add support for auto detecting core arch
- chore: enable silent mode for uci and drop useless null redirction
- style: convert Makefile to a std LuCI mk
> add support for auto detecting core arch and format fixes

- luci-app-openclash/root/etc/init.d/openclash
> fix: fake-ip TUN模式和游戏模式下的转发问题

- luci-app-openclash/luasrc/view/openclash/status.htm
[#1453](https://github.com/vernesong/OpenClash/issues/1450)
> 修复打开 dashboard 反复弹出对话框的问题

- luci-app-openclash/root/etc/config/openclash
> 同步修改配置文件中geoip为lite版本

- luci-app-openclash/root/etc/openclash/custom/openclash_custom_fake_filter.list
see https://github.com/vernesong/OpenClash/issues/1751
> feature:FFXIV相关域名加入Fake-IP域名黑名单

- luci-app-openclash/luasrc/model/cbi/openclash/settings.lua
- luci-app-openclash/root/usr/share/openclash/clash_version.sh
- luci-app-openclash/root/usr/share/openclash/openclash_core.sh
- luci-app-openclash/root/usr/share/openclash/openclash_download_rule_list.sh
- luci-app-openclash/root/usr/share/openclash/openclash_geoip.sh
- luci-app-openclash/root/usr/share/openclash/openclash_geosite.sh
- luci-app-openclash/root/usr/share/openclash/openclash_ipdb.sh
- luci-app-openclash/root/usr/share/openclash/openclash_rule.sh
- luci-app-openclash/root/usr/share/openclash/openclash_update.sh
- luci-app-openclash/root/usr/share/openclash/openclash_version.sh
- luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh
jsDelivr (cdn.jsdelivr.net) 被墙，加入 Fastly (fastly.jsdelivr.net) 的 CDN 下载源
> Add Fastly CDN

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
> 添加 Issue 模板

- luci-app-openclash/luasrc/view/openclash/sub_info_show.htm
sub_info_show.htm hidden undefined day
隐藏 undefined (剩余 undefined 天)
#2466 
patch-2
效果
> sub_info_show.htm hidden undefined day

- luci-app-openclash/root/etc/init.d/openclash
> Fix a typo in boot method

- luci-app-openclash/luasrc/view/openclash/myip.htm
- Anonymize IPs sent to `qqwry.api.skk.moe`
- Use fetch's `referrerPolicy` to simplify referrer policy handling
> refactor: anonymize ip + simplify referrerPolicy handling

- luci-app-openclash/luasrc/controller/openclash.lua
- luci-app-openclash/luasrc/view/openclash/update.htm
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
this initial commit for #1999 , #2046 and #2563 issues, here's preview. This commit excluded BACKUP button inside OpenClash - Config Manage tab
https://user-images.githubusercontent.com/20932301/180934498-f2ae0149-eac2-475b-ac0b-58952158ab4d.mp4
> Add backup options

- luci-app-openclash/root/etc/init.d/openclash
1. fix set create error if china ip route pass is empty
2. also adept to ipset if dnsmasq have NOT nftset support
> fix: set create error

- luci-app-openclash/root/etc/init.d/openclash
fix typo while add ipv6 firewall rules
> fix(init): add ipv6 firewall rules into mangle_v6 chain

- luci-app-openclash/root/etc/init.d/openclash
we should use nft_tproxy with nftables. 
fix error: failed to find a module named xt_TPROXY
> fix(init): fix typo

- luci-app-openclash/root/etc/init.d/openclash
> Fix firewall rules. Limit some chains to IPv4 only.

- luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
- luci-app-openclash/root/usr/share/openclash/yml_proxys_get.sh
- luci-app-openclash/root/usr/share/openclash/yml_proxys_set.sh
The latest version of meta supports port hopping for hy2 https://github.com/MetaCubeX/mihomo/commit/feedc9ec66b8afca3c76c82202cf9b7d69af3e75
> add Port Hopping

- luci-app-openclash/root/usr/share/openclash/openclash_debug_dns.lua
Skip Proxy Address feature relies on the openclash_debug_dns.lua script. This update  has added IPv6 support, enabling the Skip Proxy Address functionality to also support IPv6.
> IPv6 support for dns debugging and skip proxy address feature

- luci-app-openclash/root/etc/uci-defaults/luci-openclash
- luci-app-openclash/root/usr/share/ucitrack/luci-app-openclash.json
*** compatible lede
*** luci-base: conversion of ucitrack handling from uci to json. See the official commit for details:
https://github.com/openwrt/luci/commit/d5c413d2853fde0d5cec98641606a0a30f93281c
> Fixed an issue with the official latest master branch not working.

- luci-app-openclash/luasrc/model/cbi/openclash/settings.lua
- luci-app-openclash/luasrc/view/openclash/myip.htm
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
myip: Add tooltip to display full IP address on hover
China IP Route: fix typo
> myip: Add tooltip to display full IP address on hover

- luci-app-openclash/luasrc/model/cbi/openclash/servers-config.lua
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
- luci-app-openclash/root/usr/share/openclash/yml_proxys_get.sh
- luci-app-openclash/root/usr/share/openclash/yml_proxys_set.sh
See: https://github.com/MetaCubeX/mihomo/commit/fc233184fd048d0ced500d146235d11ebf6c6a4f
> Add receive window config for hy2

- luci-app-openclash/root/usr/share/openclash/res/game_rules.list
> update game rules

- luci-app-openclash/root/usr/share/openclash/res/sub_ini.list
Added four subscription conversion templates from the repository https://github.com/Aethersailor/Custom_OpenClash_Rules, which provides community templates and tutorials for OpenClash.
> chore: add more subscription conversion templates
