- luci-app-openclash/root/etc/init.d/openclash
Exclude TCP/UDP ports set by `Traffic Rules' in Openclash chains.
> Exclude TCP/UDP ports in `Traffice Rules'.

- luci-app-openclash/root/etc/init.d/openclash
Fix 'mmap: cannot allocate memory' on some firmware.
> Fix 'mmap: cannot allocate memory'.

- luci-app-openclash/luasrc/view/openclash/status.htm
修复当API获取不到IP时Dashboard打不开的情况
(如果本地网络网卡名不叫lan时获取不到ip)
(dashboard URI中如果存在hostname字段但没有值会报错)
> 修复当API获取不到IP时Dashboard打不开的情况

- luci-app-openclash/luasrc/model/cbi/openclash/settings.lua
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
- luci-app-openclash/root/etc/config/openclash
- luci-app-openclash/root/etc/init.d/openclash
- luci-app-openclash/root/usr/share/openclash/yml_change.sh
1. IPv6 TCP+UDP 都走 TProxy
2. IPv6 所有流量都经过 Clash
[luci-app-openclash_0.43.01-beta_all.ipk.zip](https://github.com/vernesong/OpenClash/files/6223564/luci-app-openclash_0.43.01-beta_all.ipk.zip)
```
$ curl -6 https://www.google.com/ -v > /dev/null
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 2404:6800:4005:80b::2004:443...
* Connected to www.google.com (2404:6800:4005:80b::2004) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: www.google.com
* Server certificate: GTS CA 1O1
* Server certificate: GlobalSign
* Using HTTP2, server …
```
> 初步实现 TProxy IPv6 透明代理

- luci-app-openclash/root/usr/share/openclash/openclash.sh
测试了下，clash 最新版本已经不支持 `!<str>` 和纯数字的格式
```
proxies:
- {name: name, server: 1.1.1.1, port: 123, type: ss, cipher: aes-256-cfb, password: 4415934295}
- {name: name, server: 1.1.1.1, port: 123, type: ss, cipher: aes-256-cfb, password: "4415934295"}
- {name: name, server: 1.1.1.1, port: 123, type: ss, cipher: aes-256-cfb, password: !<str> 4415934295}
- {name: name, server: 1.1.1.1, port: 123, type: ss, cipher: aes-256-cfb, password: !str 4415934295}
- {name: name, server: 1.1.1.1, port: 123, type: ss, cipher: aes-256-cfb, password: !!str 4415934295}
```
> fix: 修复数字密码支持

- luci-app-openclash/root/etc/init.d/openclash
Test on: OpenWrt Master SNAPSHOT
Help wanted: Test on OpenWrt 21.02 branch
修改内容:
1. 修复页面上点击'关闭OPENCLASH'时, 防火墙规则无法正常清空的问题;
> fix: firewall rule flush while stop

- luci-app-openclash/luasrc/controller/openclash.lua
/usr/lib/lua/luci/controller/openclash.lua:599: bad argument #1 to 'sub' (string expected, got nil)
subscription-userinfo missing expire
subscription-userinfo: upload= ; download=; total= ; 
只有上面三个
缺expire= ;
#2465 
自问自答
patch-1效果
> fixed subscription-userinfo missing expire

- luci-app-openclash/root/etc/init.d/openclash
修复更新后首次启动不启用 china_ip_route 就无法启动
> fix: can not start if `china_ip_route` not enabled

- luci-app-openclash/root/www/luci-static/resources/openclash/theme/idea.css
运行日志显示界面字体映射有点小问题，具体是 idea.css 中这一行：
`.cm-s-idea  { font-family: Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;}`
在一堆等宽字体后突然出现了 serif，在 Mac 上会映射为宋体。这是不应该的，因为开头排到的几个代码字体都是无衬线体，和宋体不搭配。将 serif 改为 sans-serif，问题解决。Windows 上因为排在前位的 monospace 本就映射为宋体，所以没有变化。若要搭配微软雅黑的话，把 monospace 删去即可，况且它在主流系统中完全映射不到。
另外日志显示页面还共用了配置编辑器的 font size，在此还有个建议：
/luci-app-openclash/luasrc/view/openclash/config_editor.htm 中第 4 行
`font-size: 15px`
改为 13px，与页面其他部分字体尺寸保持一致，Mac 上也不会有大号字造成渲染过粗的问题，看起来比现在要优雅一些。
> Update idea.css: optimizing font display in log

- luci-app-openclash/luasrc/controller/openclash.lua
For OpenWRT 21.02, option ifname has been renamed to device.
https://openwrt.org/releases/21.02/notes-21.02.0#new_network_configuration_syntax_and_boardjson_change
> Fix daip can not get dhcp address in OpenWRT 21.02

- luci-app-openclash/root/etc/init.d/openclash
现在等待 TUN 接口启动的 20 秒超时对于某些设备来说有点慢了（特别是 Meta 使用 GEOIPDATA 和 GEOSITE 的情况下），而且超时了没有任何提示，连失败的原因都不知道是什么，建议后续增加相关提示，这里先改为 60 秒。
> Add Tun interface wait timeout

- luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh
> fix: custom rule

- luci-app-openclash/root/etc/init.d/openclash
不需要劫持白名单外和黑名单内的设备的dns
nftables的部分我没改。。。那边不会写
改动的部分只有这两个判断中添加tcp53、udp53劫持那两句，diff会显示这么多是因为我把`#lan_ac`创建黑白名单那几段挪到创建劫持dns规则的前面去了。
```bash
if [ "$enable_redirect_dns" -eq 1 ]; then
elif [ "$enable_redirect_dns" -eq 2 ]; then
fi
```
> Do not hijack dns outside the ac list

- luci-app-openclash/root/usr/share/openclash/yml_rules_change.sh
解决覆写URL-Test 策略组切换灵敏度(ms)、测速（连通性）间隔修改(s) 不生效的问题。
时间不够，没去研究clash源码，大概率是这个问题。由于加了 ```‘ ’``` 导致读取yaml时类型不对，导致失效。会出现每次url-test都会切换节点。网络就不稳定了。
> fix: overwrite  url-test interval not work

- luci-app-openclash/root/usr/share/openclash/yml_proxys_set.sh
close: #3296
before:
```yaml
proxies:
- type: vmess
alterId: 0
cipher: auto
udp: false
global-padding: false
authenticated-length: false
skip-cert-verify: true
tls: false
ip-version: "dual"
tfo: false
smux:
enabled: false
```
Linter error:
```
Error : bad indentation of a mapping entry at line 12, column 3:
smux:
^
Line : undefined  undefined
```
After:
```yaml
proxies:
- type: vmess
alterId: 0
cipher: auto
udp: false
global-padding: false
authenticated-length: false
skip-cert-verify: true
tls: false
ip-version: "dual"
tfo: false
smux:
enabled: false
```
> fix: #3296 bad indentation of smux

- luci-app-openclash/luasrc/view/openclash/sub_info_show.htm
Switch your operating system to dark mode.
I used the color variable `-dark-gray` as its light mode for the font color.
> fix: accessibility in dark mode

- luci-app-openclash/luasrc/model/cbi/openclash/settings.lua
* https://github.com/MetaCubeX/Clash.Meta/blob/Alpha/constant/tun.go#L69
> feat: add mixed stack

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
ISSUE_TEMPLATE 大致修改内容
1. 新建issue时增加了分流，目的可以理解成间接告知用户 OpenClash 和 Clash 等项目的关系，减少一些无意义的issue
2. 两个模板均修改了确认项，顺便挖了个坑，间接促使用户认真对待自己的issue
3. feature模板仅保留一个必填和一个选填，原本的两必填两选填没用户用到的同时也导致issue排版混乱
4. bug模板增加了调试日志的获取方式，填入内容改成了代码块并增加一些说明，防止issue排版混乱，并要求用户认真对待
5. bug模板调换了描述bug和复现bug的顺序
6. bug模板系统环境方面增加了点内容
7. 提高Disscuss的利用率
> 整理并修改 ISSUE_TEMPLATE

- luci-app-openclash/root/etc/uci-defaults/luci-openclash
修正将utun添加到防火墙区域的方式
使用`uci add_list`而不是`uci set`
> fix add_utun_firewall_zone

- luci-app-openclash/root/etc/config/openclash
Here are the changes:
remove option port
They all use standard ports, so reassigning ports is not necessary
add quad9-DNS to the fallback group
add google DoH to the fallback group
rearrange the order by option type
change to udp type
google dns of tls type already exists
reorder option to the fallback group
> config: readjust the fallback group

- luci-app-openclash/root/etc/init.d/openclash
`$lan_interface_name` is the name of the LAN interface, not a path.
> fix(init):fix typo

- luci-app-openclash/root/usr/share/openclash/res/game_rules.list
Handle single-quote syntax in game rules list and use it as the filename.
> fix: Handle single-quote syntax in game rules list

- luci-app-openclash/root/etc/init.d/openclash
当前如果想添加端口范围会报错
root@ImmortalWrt:~# nft add element inet fw4 common_ports { "0-3477" } Error: You must add 'flags interval' to your set declaration if you want to add range elements add element inet fw4 common_ports { 0-3477 }
^^^^^^
添加 flags interval;  以后即可正常添加端口范围，且兼容原来的配置方法
设置常用端口  0-3477, 3479-65534, 65535 后的结果
set common_ports {
type inet_service
flags interval
elements = { 0-3477, 3479-65534, 65535 }
}
> feat: support port range in common_ports

- luci-app-openclash/Makefile
> luci-app-openclash: Fix `$` sign not escaping correctly.

- luci-app-openclash/root/etc/init.d/openclash
完善nftables防火墙规则的导入，包括添加对IPv6后缀匹配的支持。
1）由于有设备需要开放端口，且公网IPv6的前缀时常变动，我在OpenWrt上添加了匹配IPv6后缀的规则。但OpenClash并没有成功导入这一规则，因为nft规则有特定的格式要求，需要进行转换。以往，有需要的朋友会通过自定义脚本来解决 https://github.com/vernesong/OpenClash/issues/3929 https://github.com/vernesong/OpenClash/issues/3088#issuecomment-1463930866 ，而完善代码后，包含端口的这类规则将可以自动读取。
PS. 目前的代码还不支持导入只有IP没有端口的防火墙规则。这是为什么呢？看起来这意味着openclash_mangle_output(_v6)链要return来自所有端口的流量，这应该会带来问题，但我不太理解为什么要这样。如果能通过其他办法规避问题，我可以试着修改，比如在此情况下只添加openclash_mangle链的规则。
2）如果nft规则中出现多个IP，OpenClash会无法导入该规则，将IP之间的空格改为逗号即可解决。
3）如果nft规则中出现端口范围，OpenClash会无法导入该规则。脚本中提示称这可能影响正常流量经过核心，并将其return，但后续在iptables的相关部分，又存在将端口范围的”-“改成”:“的代码，这还有意义吗？如果根据提示，在”黑白名单“中添加绕过的端口，这将无法区分来源的IP。我觉得有提示已经足够了，直接return可能不符合大家预期的行为。但如果作者有更多考虑，可以将其恢复，我再想其他办法解决问题~
不论如何，非常感谢开发者的辛勤付出！
> Enhance nft firewall rules; add support for IPv6 suffix matching

- luci-app-openclash/root/etc/init.d/openclash
repeat use of `procd_set_param` will overwrite the param, so we need to use `procd_append_param` after first set
> fix: set procd env correctly

- luci-app-openclash/root/etc/init.d/openclash
如果 dnsmasq 没有启用（比如旁路由可能不使用 dnsmasq 作为 DNS 服务），避免重启它以造成冲突或其他问题。
#4672 on dev branch
> feat: restart only when dnsmasq is enabled

- luci-app-openclash/luasrc/model/cbi/openclash/settings.lua
- luci-app-openclash/po/zh-cn/openclash.zh-cn.po
Fix two issues in Chinese translations:
1. Add missing spaces between Chinese and English text for better readability
2. Fix duplicate "Custom GeoSite URL" translation key in Geo ASN settings
> Fix Chinese translation spacing and duplicate translation key
